my side of the story
floridop/MNXB01-fairytale pull request #119
Opened 2024-10-02 14:51 UTC by Takumi0104

2024-10-28 11:01 UTC, floridop commented
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 2 slides 102-114 and integrate those changes?
Read the theory in slides 102-104 and then start the practice 
by synchronizing your local and remote *main* with my *upstream main* as described in slide 105.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
You have time until the **30th of October at 12:00**. 
If you can't make it by that time or you are done before the deadline, 
please add a comment in GitHub so that I can progress with another student.

2024-10-30 10:48 UTC, Takumi0104 commented
Hi. I couldn't do this task until deadline...

2024-10-30 15:56 UTC, floridop commented
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 2 slides 102-114 and integrate those changes?
Read the theory in slides 102-104 and then start the practice 
by synchronizing your local and remote *main* with my *upstream main* as described in slide 105.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
The merges will be approved according to arrival time starting from October 30th, 17:00, 
so expect that you need to merge several times after that time.
If I do not approve the changes you will be asked to update the content.

2024-10-30 18:30 UTC, Takumi0104 commented
Hi. I couldn't be in time for the deadline until 17:00. So is my homework not possible to be resubmitted again anymore? I want to have a chance to merge again...

2024-11-02 14:39 UTC, floridop commented
Hi Takumi. You misunderstood my text. What I mean is that there is no deadline anymore, you can resolve the conflict anytime you want.

2024-11-08 09:54 UTC, floridop requested changes
Hi Takumi. Please removed the marked lines or I cannot approve your PR.

2024-11-08 09:54 UTC, floridop commented on fairytale.md
> +<<<<<<< HEAD
This line represents the beginning of your changes. Maybe it was not clear in tutorial 2 slides 110-111, but you need to **remove** these lines when you perform the merge.

2024-11-08 09:54 UTC, floridop commented on fairytale.md
> +=======
This line represents the beginning of your changes. Maybe it was not clear in tutorial 2 slides 110-111, but you need to remove these lines when you perform the merge.

2024-11-08 09:54 UTC, floridop commented on fairytale.md
> +>>>>>>> main
This line represents the beginning of your changes. Maybe it was not clear in tutorial 2 slides 110-111, but you need to remove these lines when you perform the merge.

2024-11-08 12:30 UTC, Takumi0104 commented
Hi, Florido! 
I changed the script as you mentioned that I forgot the instructions on pages 110-111.
Please check whether my modified script is correct or not!

2024-11-08 16:42 UTC, merged

2024-11-08 16:43 UTC, floridop commented
Thanks for your contribution! Task 2 completed! See canvas for results