my side of the story
floridop/MNXB01-fairytale pull request #49
Opened 2022-09-16 13:54 UTC by fredholmP

2022-10-11 12:33 UTC, floridop commented
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 5 slides 82-96 and integrate those changes?
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do not modify
the content of what others have written.
You have time until the 13th of October at 14:40. 
If you can't make it by that time or you are done before the deadline, 
please add a comment in github so that I can progress with another student.

2022-10-12 07:46 UTC, fredholmP commented
I have now made changes to make the stories compatible.

2022-10-12 11:06 UTC, floridop requested changes
Please check comment at line 37 and take action

2022-10-13 10:54 UTC, fredholmP commented
I have merged the two stories as suggested.

2022-10-13 10:54 UTC, fredholmP commented on fairytale.md
>  There once lived a man, in Russia long ago, before this story was even
I have merged the two stories as suggested.

2022-10-13 10:56 UTC, fredholmP commented on fairytale.md
>  There once lived a man, in Russia long ago, before this story was even
*Not merged as in a github merge but as in rewritten a combination of both of them in the more colloquial meaning.

2022-10-13 11:53 UTC, merged

2022-10-13 11:53 UTC, floridop commented
Thanks for your contribution! Scenario A completed! See canvas for results